### ISSUE TITLE
Only one matrix working after reset

### ISSUE THREAD

**Issue by alfem** [SensorsIot/MAX7219-4-digit-display-Library-for-ESP8266-#2]
I am using four in a row 8x8 led matrix.

Everything works fine, but if I disconnect the nodemcu from my laptop -after programming it- and plug it again, only one or two 8x8 matrix work. When I reload the program (using the Arduino IDE), it works perfect again.

Any clues?

**Comment by SensorsIot** [comment]
Unfortunately, no :-(

**Comment by thisismyusername123445** [comment]
try adding a 2 second delay before initializing the display in your setup, like this:
void setup() 
{
  delay(2000);

solved the problem for me.
